name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Configure environment
        run: |
          # Setup Java paths
          echo "JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64" >> $GITHUB_ENV
          echo "PATH=/usr/lib/jvm/temurin-17-jdk-amd64/bin:$PATH" >> $GITHUB_ENV
          
          # Setup Android paths
          ANDROID_HOME=/usr/local/lib/android/sdk
          ANDROID_NDK_HOME=$ANDROID_HOME/ndk/27.2.12479018
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          echo "ANDROID_SDK_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
          
          # Setup build environment
          echo "USE_CCACHE=1" >> $GITHUB_ENV
          echo "NDK_CCACHE=/usr/bin/ccache" >> $GITHUB_ENV
          echo "JAVA_OPTS=-Xmx4096m" >> $GITHUB_ENV
          echo "PATH=$PATH:~/.local/bin" >> $GITHUB_ENV
          
          # Verify Java installation
          echo "=== Java Environment ==="
          java -version

      - name: Setup Android SDK with JAXB support
        run: |
          # Asegurar que JAXB está en el classpath
          JAXB_LIBS="/usr/share/java/jaxb-api.jar:/usr/share/java/jaxb-runtime.jar:/usr/share/java/jakarta.xml.bind-api.jar"
          export CLASSPATH=$JAXB_LIBS:$CLASSPATH
          
          # Configurar sdkmanager con JAXB
          yes | CLASSPATH=$JAXB_LIBS $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            --sdk_root=$ANDROID_HOME \
            --licenses
          
          CLASSPATH=$JAXB_LIBS $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            --sdk_root=$ANDROID_HOME \
            "platforms;android-33" \
            "build-tools;33.0.0" \
            "ndk;27.2.12479018"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip libtool automake autoconf build-essential python3-pip python3-dev git libffi-dev libssl-dev
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
          sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          sudo apt-get install -y default-jdk wget lsb-release software-properties-common
          sudo apt-get install -y ccache
          
          # Instalar módulos JAXB necesarios
          sudo apt-get install -y jaxb \
                                libjaxb-java \
                                libjakarta-xml-bind-api-java \
                                libxml-commons-external-java \
                                libxml-commons-resolver1.1-java
          
          # Configurar classpath para JAXB
          JAXB_LIBS="/usr/share/java/jaxb-api.jar:/usr/share/java/jaxb-runtime.jar:/usr/share/java/jakarta.xml.bind-api.jar"
          echo "CLASSPATH=$JAXB_LIBS:$CLASSPATH" >> $GITHUB_ENV
          
          # Verificar instalación de JAXB
          ls -l /usr/share/java/jaxb* || true
          ls -l /usr/share/java/jakarta* || true

      - name: Prepare buildozer.spec
        run: |
          cat > buildozer.spec << 'EOF'
          [app]
          title = RemoteControl
          package.name = remotecontrol
          package.domain = org.caito55
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          version = 0.1
          requirements = python3,kivy,flet==0.15.0,kivymd,pillow,websockets,asyncio
          orientation = portrait
          osx.python_version = 3
          android.archs = arm64-v8a
          android.allow_backup = True
          android.api = 33
          android.minapi = 21
          android.ndk_api = 21
          android.sdk_path = /usr/local/lib/android/sdk
          android.ndk_path = /usr/local/lib/android/sdk/ndk/27.2.12479018
          android.ant_path = /usr/bin/ant
          android.permissions = INTERNET
          android.debug = 1
          android.accept_sdk_license = True
          android.gradle_dependencies = org.chromium:androidx.webkit:1.4.0
          p4a.branch = develop
          p4a.bootstrap = sdl2
          android.java_version = 17
          
          [buildozer]
          log_level = 2
          warn_on_root = 0
          android_sdk_path = /usr/local/lib/android/sdk
          android_ndk_path = /usr/local/lib/android/sdk/ndk/27.2.12479018
          android_api = 33
          java_home = /usr/lib/jvm/temurin-17-jdk-amd64
          EOF

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip wheel
          pip install --upgrade buildozer Cython==0.29.33
          sudo chown -R $USER:$USER .
          sudo apt-get install -y automake
          ccache -M 50G

      - name: Setup build directories
        run: |
          # Crear y configurar directorios necesarios
          sudo mkdir -p /home/runner/.buildozer
          sudo mkdir -p /home/runner/.gradle
          sudo chown -R $USER:$USER /home/runner/.buildozer
          sudo chown -R $USER:$USER /home/runner/.gradle
          sudo chown -R $USER:$USER $ANDROID_HOME

      - name: Build APK
        env:
          BUILDOZER_WARN_ON_ROOT: 0
          SKIP_JDK_VERSION_CHECK: true
        run: |
          # Verificar entorno final
          echo "=== Build Environment ==="
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          echo "ANDROID_HOME: $ANDROID_HOME"
          
          # Limpiar caché si existe
          rm -rf .buildozer || true
          
          # Construir APK con log detallado
          buildozer -v android debug
      

      
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: RemoteControl-APK
          path: bin/*.apk
