name: Build APK

on:
  push:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install flet

    - name: Build APK
      run: |
        pip install buildozer
        mkdir flet_build
        flet pack main.py --name RemoteControlApp --app-version 1.0.0 --platform android --output flet_build

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: RemoteControlApp-APK
        path: flet_build/dist/*.apk
