name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip libtool automake autoconf build-essential python3-pip python3-dev git libffi-dev libssl-dev
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
          sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          sudo apt-get install -y default-jdk wget lsb-release software-properties-common
          sudo apt-get install -y ccache

      - name: Prepare buildozer.spec
        run: |
          cat > buildozer.spec << 'EOF'
          [app]
          title = RemoteControl
          package.name = remotecontrol
          package.domain = org.caito55
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          version = 0.1
          requirements = python3,kivy,flet==0.15.0,kivymd,pillow,websockets,asyncio
          orientation = portrait
          osx.python_version = 3
          android.archs = arm64-v8a
          android.allow_backup = True
          android.api = 33
          android.minapi = 21
          android.ndk_api = 21
          android.permissions = INTERNET
          android.debug = 1
          android.accept_sdk_license = True
          android.gradle_dependencies = org.chromium:androidx.webkit:1.4.0
          p4a.branch = develop
          p4a.bootstrap = sdl2
          
          [buildozer]
          log_level = 2
          warn_on_root = 0
          EOF

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Accept Android SDK licenses
        run: |
          yes | sudo $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          sudo $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0"
        
      - name: Install Buildozer and build APK
        run: |
          python -m pip install --upgrade pip wheel
          pip install --upgrade buildozer Cython==0.29.33
          export PATH=$PATH:~/.local/bin
          sudo chown -R $USER:$USER .
          sudo apt-get install -y automake
          
          # Configurar ccache
          export USE_CCACHE=1
          export NDK_CCACHE=/usr/bin/ccache
          ccache -M 50G
          
          # Configurar variables de entorno
          export JAVA_HOME=/opt/java/17
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export JAVA_OPTS='-Xmx4096m'
          
          # Construir APK
          buildozer android debug -v
      

      
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: RemoteControl-APK
          path: bin/*.apk
