name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip libtool automake autoconf

      - name: Prepare .buildozer directory
        run: |
          mkdir -p .buildozer
          echo '[app]' > buildozer.spec
          echo 'title = RemoteControl' >> buildozer.spec
          echo 'package.name = remotecontrol' >> buildozer.spec
          echo 'package.domain = org.caito55' >> buildozer.spec
          echo 'source.include_exts = py,png,jpg,kv,atlas' >> buildozer.spec
          echo 'version = 0.1' >> buildozer.spec
          echo 'requirements = python3,flet>=0.15.0,kivymd' >> buildozer.spec
          echo 'orientation = portrait' >> buildozer.spec
          echo 'osx.python_version = 3' >> buildozer.spec
          echo 'android.archs = armeabi-v7a, arm64-v8a' >> buildozer.spec
          echo 'android.ndk_api = 21' >> buildozer.spec
          echo 'android.minapi = 21' >> buildozer.spec
          echo 'android.permissions = INTERNET' >> buildozer.spec
          echo 'android.debug = 1' >> buildozer.spec

      - name: Build APK using Docker (Buildozer)
        run: |
          docker run --rm -v "$PWD":/home/user/hostcwd -w /home/user/hostcwd kivy/buildozer buildozer android debug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: RemoteControl-APK
          path: bin/*.apk
